[build]
  publish = "."

[[headers]]
  for = "/program/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"

[[headers]]
  for = "/p/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/program/*"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/p/*"
  to = "/app.html"
  status = 200
