/**
 * FAQ content — single source of truth for /faq/ and landing #faq.
 * Edit here, then run: npm run build:faq
 * Do not edit FAQ between markers in index.html (generated by faq/build.mjs).
 * Order: questions people actually search for first.
 * Answers use "powerlift.ing" (not "it" / "the app") for brand clarity.
 * Answers may include simple HTML: <a>, <code>, <strong>, <p>, <ul>, <li>.
 */

export const FAQ_SECTIONS = [
  {
    id: "start",
    title: "Getting started",
    items: [
      {
        q: "What is powerlift.ing?",
        a: "<p>powerlift.ing is a free powerlifting program builder you use in your browser. Plan your weeks, log squat, bench, and deadlift work, then share the whole plan as one open link — so lifters and coaches can spread real programming, not gatekeep it. No spreadsheet and no sign-up to start.</p>",
      },
      {
        q: "Is powerlift.ing free?",
        a: "<p>Yes. powerlift.ing lets you build, edit, and share programs for free. Paid extras like saved accounts or shorter links may come later, but the core builder is meant to stay free.</p>",
      },
      {
        q: "Do I need an account for powerlift.ing?",
        a: "<p>No. Open <a href=\"/app\">powerlift.ing</a>, start typing, and share when you are ready. Logins for saving many programs are planned, but powerlift.ing does not require an account today.</p>",
      },
      {
        q: "How do I make a powerlifting program on powerlift.ing?",
        a: "<p>Open <a href=\"/app\">powerlift.ing</a>. You get a starter week. Name your training block, add days with <strong>Add Day</strong>, then fill in exercises, sets, reps, weight, % of max, and RPE. powerlift.ing saves your work in the link as you type.</p>",
      },
      {
        q: "Does powerlift.ing work on my phone?",
        a: "<p>Yes. powerlift.ing is built for phones first. Turn your phone sideways if you want to see more columns at once.</p>",
      },
    ],
  },
  {
    id: "sharing",
    title: "Sharing your program",
    items: [
      {
        q: "How do I share my program on powerlift.ing?",
        a: "<p>Tap the <strong>share</strong> button at the top of powerlift.ing. Your link is copied. Paste the link in a text, email, or DM like any other URL. More detail in <a href=\"/blog/how-sharing-works/\">how sharing works</a>.</p>",
      },
      {
        q: "Can anyone with my link open my program on powerlift.ing?",
        a: "<p>Yes — and that is the point. powerlift.ing puts your full program in one link so anyone you share it with can open it instantly: an athlete, a training partner, a forum, or a lifter learning from your block. No login wall, no “request access.” powerlift.ing is built to open up powerlifting knowledge. When paid plans launch, powerlift.ing will offer <strong>private programs</strong> for coaches who want them; open one-link sharing stays the default for free use.</p>",
      },
      {
        q: "Does my powerlift.ing link change when I edit my program?",
        a: "<p>Yes. powerlift.ing updates the link as you type, so the link always matches what is on screen. Tap share again if you want to send a fresh copy after big changes.</p>",
      },
      {
        q: "Why is my powerlift.ing share link so long?",
        a: "<p>powerlift.ing stores your whole program inside the link. Bigger programs make longer links. Some chat apps cut off long links — try email, Notes, or a shorter program. Shorter links for powerlift.ing are on the way.</p>",
      },
      {
        q: "I lost my powerlift.ing link. Can you recover my program?",
        a: "<p>No. powerlift.ing does not store your program on its servers. Save important links in your notes or bookmarks.</p>",
      },
      {
        q: "My shared powerlift.ing program will not open. What should I try?",
        a: "<ul><li>Ask for a new copy of the link — the message may have cut the link off.</li><li>Open the link in Safari or Chrome, not inside another app’s preview.</li><li>If the program is huge, try splitting the program into two blocks in powerlift.ing.</li></ul>",
      },
      {
        q: "Will old powerlift.ing share links still work?",
        a: "<p>Yes. Older <code>/p/…</code> and <code>#/p/…</code> links still open in powerlift.ing. New shares use <code>/app/…</code>.</p>",
      },
    ],
  },
  {
    id: "builder",
    title: "Building your program",
    items: [
      {
        q: "How do I add weeks and training days on powerlift.ing?",
        a: "<p>Use the week controls in powerlift.ing to add weeks. On each week, tap <strong>Add Day</strong> (up to seven days). Delete a day with the trash icon on that day.</p>",
      },
      {
        q: "What is a mesocycle on powerlift.ing?",
        a: "<p>On powerlift.ing, a mesocycle is a training block — like a hypertrophy phase, strength block, or meet prep. Pick or rename the block from the mesocycle menu. Weeks belong to the block you have selected.</p>",
      },
      {
        q: "How do I set my squat, bench, and deadlift maxes on powerlift.ing?",
        a: "<p>In powerlift.ing, tap <strong>Config</strong> (the sliders icon). Enter your one-rep maxes for squat, bench, deadlift, and any custom lifts. powerlift.ing can walk you through maxes the first time you open powerlift.ing.</p>",
      },
      {
        q: "How do percentages and weight work on powerlift.ing?",
        a: "<p>After you set a max in powerlift.ing, typing a <strong>% of max</strong> fills in <strong>weight</strong>, and typing weight fills in the percent. RPE stays separate — you enter that yourself. See <a href=\"/blog/programming-with-percentages-and-rpe/\">percentages and RPE</a> for examples.</p>",
      },
      {
        q: "Can I use lbs or kg on powerlift.ing?",
        a: "<p>Yes. Switch units in the week bar in powerlift.ing. Your weights and maxes convert so the block stays consistent. Your powerlift.ing share link keeps the units you picked.</p>",
      },
      {
        q: "Can I add pause bench and other variations on powerlift.ing?",
        a: "<p>Yes. Type any exercise name in powerlift.ing. Names like pause bench tie to your bench max. Add other lifts in Config if they need their own max.</p>",
      },
    ],
  },
  {
    id: "coaches",
    title: "For coaches",
    items: [
      {
        q: "Can I send a powerlift.ing program to an athlete?",
        a: "<p>Yes. Build the block in powerlift.ing, share the link, and your athlete opens the link on phone or laptop. They see the same grid you built.</p>",
      },
      {
        q: "Can my athlete change a program on powerlift.ing?",
        a: "<p>Anyone with the link can edit in powerlift.ing in the browser. There is no view-only mode yet. Send a new link after review if you want a clean copy.</p>",
      },
      {
        q: "Is powerlift.ing better than a spreadsheet?",
        a: "<p>For many coaches, powerlift.ing is easier on mobile: one link, no formulas, and columns for sets, reps, %, RPE, and rest. Spreadsheets are still great if you need heavy custom math.</p>",
      },
    ],
  },
  {
    id: "your-data",
    title: "Your data",
    items: [
      {
        q: "Where does powerlift.ing store my program?",
        a: "<p>While you edit, powerlift.ing keeps your program in the link and in your browser. powerlift.ing does not keep a copy of anonymous programs on its servers today — your link <em>is</em> how the program travels.</p>",
      },
      {
        q: "Will my powerlift.ing link show up on Google by itself?",
        a: "<p>powerlift.ing does not auto-list individual shared program URLs in Google search — that keeps search focused on guides and templates, not random personal links. You can still post your link anywhere you want (social, forums, email, team chats) so people get the full program in one tap.</p>",
      },
      {
        q: "Is powerlift.ing medical or coaching advice?",
        a: "<p>No. powerlift.ing is a planning tool only. Talk to a coach or doctor about pain, injury, or what you should lift.</p>",
      },
    ],
  },
  {
    id: "coming-soon",
    title: "Coming soon",
    items: [
      {
        q: "Will powerlift.ing have free program templates?",
        a: "<p>Yes — classics like 5/3/1 and starter blocks are planned at <strong>/programs/</strong> on powerlift.ing. They will open in the same editor.</p>",
      },
      {
        q: "Will powerlift.ing let me save programs to an account?",
        a: "<p>Yes, that is planned so you can keep many programs in one place on powerlift.ing. Open one-link sharing without an account will still work.</p>",
      },
      {
        q: "Will powerlift.ing offer private programs?",
        a: "<p>Yes — planned for paid plans. Coaches and lifters who want password-protected or non-public blocks will get that option. Free powerlift.ing will keep celebrating open links so programming knowledge stays easy to pass along.</p>",
      },
    ],
  },
];
