#!/bin/bash
# PostgreSQL for Panax multisite platform (self-hosted on droplet).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
# shellcheck source=platform-paths.sh
source "$REPO_ROOT/infra/server/platform-paths.sh"
ENV_FILE="${PANAX_ETC_DIR}/postgrest.env"
MIGRATIONS_DIR="$REPO_ROOT/services/db/migrations"

export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq postgresql postgresql-contrib

install -d -m 0750 -o root -g postgres "${PANAX_ETC_DIR}"
AUTH_PASS="$(openssl rand -hex 24)"

sudo -u postgres createdb "${PANAX_DB_NAME}" 2>/dev/null || true

run_migration() {
  local file="$1"
  echo "Applying $(basename "$file")..."
  sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${PANAX_DB_NAME}" -f - <"$file"
}

for file in "$MIGRATIONS_DIR"/[0-9][0-9][0-9]_*.sql; do
  base=$(basename "$file")
  if [[ "$base" == "009_drop_legacy_events.sql" && "${APPLY_DROP_LEGACY:-0}" != "1" ]]; then
    echo "Skipping $base (set APPLY_DROP_LEGACY=1 after RPC smoke test)"
    continue
  fi
  if [[ "$base" == "012_rename_nocodb_role.sql" ]]; then
    continue
  fi
  run_migration "$file"
done

sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${PANAX_DB_NAME}" <<SQL
ALTER ROLE authenticator WITH LOGIN PASSWORD '$AUTH_PASS';
SQL

cat > "$ENV_FILE" <<EOF
# Generated by install-postgres.sh — do not commit
PGRST_DB_URI=postgres://authenticator:${AUTH_PASS}@127.0.0.1:5432/${PANAX_DB_NAME}
PGRST_DB_SCHEMAS=public
PGRST_DB_ANON_ROLE=web_anon
PGRST_SERVER_HOST=127.0.0.1
PGRST_SERVER_PORT=3000
EOF
chown root:postgres "$ENV_FILE"
chmod 640 "$ENV_FILE"

systemctl enable postgresql
systemctl restart postgresql
echo "PostgreSQL ready: database=${PANAX_DB_NAME} env=${ENV_FILE}"
