#!/bin/bash
# PostgreSQL for itrain.ing multisite platform (self-hosted on droplet).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
DB_NAME=itrain
ENV_FILE=/etc/itrain/postgrest.env
MIGRATIONS_DIR="$REPO_ROOT/services/db/migrations"

export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq postgresql postgresql-contrib

install -d -m 0750 root/postgres /etc/itrain
AUTH_PASS="$(openssl rand -hex 24)"

sudo -u postgres createdb "$DB_NAME" 2>/dev/null || true

run_migration() {
  local file="$1"
  echo "Applying $(basename "$file")..."
  sudo -u postgres psql -v ON_ERROR_STOP=1 -d "$DB_NAME" -f - <"$file"
}

# Ordered migrations (001 bootstrap; 009 legacy drop optional via env)
for file in "$MIGRATIONS_DIR"/[0-9][0-9][0-9]_*.sql; do
  base=$(basename "$file")
  if [[ "$base" == "009_drop_legacy_events.sql" && "${APPLY_DROP_LEGACY:-0}" != "1" ]]; then
    echo "Skipping $base (set APPLY_DROP_LEGACY=1 after RPC smoke test)"
    continue
  fi
  run_migration "$file"
done

sudo -u postgres psql -v ON_ERROR_STOP=1 -d "$DB_NAME" <<SQL
ALTER ROLE authenticator WITH LOGIN PASSWORD '$AUTH_PASS';
SQL

cat > "$ENV_FILE" <<EOF
# Generated by install-postgres.sh — do not commit
PGRST_DB_URI=postgres://authenticator:${AUTH_PASS}@127.0.0.1:5432/${DB_NAME}
PGRST_DB_SCHEMAS=public
PGRST_DB_ANON_ROLE=web_anon
PGRST_SERVER_HOST=127.0.0.1
PGRST_SERVER_PORT=3000
EOF
chmod 600 "$ENV_FILE"

systemctl enable postgresql
systemctl restart postgresql
echo "PostgreSQL ready: database=$DB_NAME env=$ENV_FILE"
