#!/bin/bash
# NocoDB on localhost:8080 — visual admin for Panax Postgres (does not replace PostgREST).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
# shellcheck source=platform-paths.sh
source "$REPO_ROOT/infra/server/platform-paths.sh"
ENV_FILE="${PANAX_ETC_DIR}/nocodb.env"
DATA_DIR="${PANAX_DATA_DIR}/nocodb"
MIGRATION="$REPO_ROOT/services/db/migrations/010_nocodb_reader.sql"
IMAGE=nocodb/nocodb:latest

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root: sudo $0" >&2
  exit 1
fi

[[ -f "${PANAX_ETC_DIR}/postgrest.env" ]] || {
  echo "Run install-postgres.sh first (${PANAX_DB_NAME} database required)." >&2
  exit 1
}

export DEBIAN_FRONTEND=noninteractive
if ! command -v docker >/dev/null 2>&1; then
  apt-get update -qq
  apt-get install -y -qq docker.io
  systemctl enable --now docker
fi

install -d -m 0750 -o root -g root "$DATA_DIR"

NOCODB_PASS="$(openssl rand -hex 24)"
JWT_SECRET="$(openssl rand -hex 32)"

echo "Applying 010_nocodb_reader.sql..."
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${PANAX_DB_NAME}" -f - <"$MIGRATION"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${PANAX_DB_NAME}" -f - <"$REPO_ROOT/services/db/migrations/012_rename_nocodb_role.sql" 2>/dev/null || true
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${PANAX_DB_NAME}" <<SQL
ALTER ROLE panax_nocodb WITH LOGIN PASSWORD '${NOCODB_PASS}';
SQL

cat > "$ENV_FILE" <<EOF
# Generated by install-nocodb.sh — do not commit
NC_AUTH_JWT_SECRET=${JWT_SECRET}
NC_PUBLIC_URL=http://127.0.0.1:8080
NOCODB_PG_USER=panax_nocodb
NOCODB_PG_PASSWORD=${NOCODB_PASS}
NOCODB_PG_HOST=host.docker.internal
NOCODB_PG_PORT=5432
NOCODB_PG_DATABASE=${PANAX_DB_NAME}
EOF
chmod 600 "$ENV_FILE"

cat > /etc/systemd/system/nocodb.service <<EOF
[Unit]
Description=NocoDB admin UI (Panax platform)
After=docker.service postgresql.service
Wants=docker.service

[Service]
ExecStartPre=-/usr/bin/docker rm -f nocodb
ExecStart=/usr/bin/docker run --name nocodb \\
  --rm \\
  -p 127.0.0.1:8080:8080 \\
  --add-host=host.docker.internal:host-gateway \\
  -v ${DATA_DIR}:/usr/app/data \\
  -e NC_AUTH_JWT_SECRET=${JWT_SECRET} \\
  -e NC_PUBLIC_URL=http://127.0.0.1:8080 \\
  -e NC_DISABLE_TELE=true \\
  ${IMAGE}
ExecStop=/usr/bin/docker stop -t 10 nocodb
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
docker pull "$IMAGE"
systemctl enable nocodb
systemctl restart nocodb

for i in $(seq 1 30); do
  if curl -sf "http://127.0.0.1:8080/" >/dev/null 2>&1; then
    echo "NocoDB ready: http://127.0.0.1:8080"
    echo "Credentials: $ENV_FILE"
    echo "Next: connect external DB — see docs/NOCODB.md"
    exit 0
  fi
  sleep 2
done

journalctl -u nocodb -n 30 --no-pager
exit 1
