/** Brand definitions for suite sites (marketing surfaces). */

export const SITE_BRANDS = {
  powerbuilding: {
    key: "powerbuilding",
    domain: "powerbuild.ing",
    slug: "powerbuild",
    wordmarkName: "Powerbuild",
    tld: "ing",
    comment: "powerbuild.ing — design tokens (powerbuilding / hypertrophy)",
    primary: "#ef4444",
    primaryDim: "#c81e1e",
    chalk: "#f5f2ee",
    iron: "#0a0a0c",
    steel: "#141418",
    rack: "#1c1c22",
    rackUp: "#26262e",
    fontDisplay: '"Share Tech", system-ui, sans-serif',
    fontSans: '"DM Sans", system-ui, -apple-system, sans-serif',
    fontMono: '"IBM Plex Mono", ui-monospace, monospace',
    fontDisplayFallback: '"Arial Narrow", "Helvetica Neue Condensed", system-ui, sans-serif',
    fontSansFallback: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
    fontMonoFallback: 'ui-monospace, "Cascadia Mono", "Segoe UI Mono", monospace',
    googleFontsUrl:
      "https://fonts.googleapis.com/css2?family=Share+Tech&family=DM+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@500;600&display=swap",
    appGoogleFontsUrl:
      "https://fonts.googleapis.com/css2?family=Share+Tech&family=DM+Sans:ital,wght@0,400;0,500;0,600;0,700;1,400&family=IBM+Plex+Mono:wght@500;600&display=swap",
    themeColorLight: "#f5f2ee",
    themeColorDark: "#0a0a0c",
    sport: "powerbuilding",
    sportTitle: "Powerbuilding",
    productLine: "Powerbuilding program builder",
    productShort: "powerbuilding program builder",
    heroEm: "Share your hypertrophy block in one link",
    heroLead:
      "Plan mesocycles, weeks, and training days — sets, reps, load, %1RM, RPE, and rest. Built for volume and growth on your phone.",
    featuresLead: "Hypertrophy blocks, strength phases, or deloads — without leaving the browser.",
    featuresCard1: "Hypertrophy, strength, deload — organize blocks and weeks in one view.",
    featuresCard2: "Sets, reps, load (lb/kg), %1RM, RPE, rest, and exercise variations.",
    programsTitle: "Free powerbuilding programs",
    programsLead:
      "Free strength and hypertrophy templates from powerbuild.ing. Pick a card, open it in the builder, edit anything, and share your version as one link. Use the <strong>Blank program</strong> card to start from scratch.",
    programsMeta:
      "Free powerbuilding program templates on powerbuild.ing: splits, volume blocks, and strength templates. Open in the builder and share one link.",
    programsCardEditor: "Open in the powerbuild.ing editor",
    faqLandingLead: "Common questions about building, sharing, and using programs on powerbuild.ing",
    faqPageMeta:
      "Frequently asked questions about powerbuild.ing: free program builder, open sharing, %1RM maxes, coaches, and technical support.",
    tagline: "Free powerbuilding program builder. Share whole programs as one open link.",
    description:
      "The best free powerbuilding program builder. Plan mesocycles, track sets, reps, RPE, and %1RM — then share your whole training block in one link.",
    keywords:
      "powerbuilding program, hypertrophy program builder, strength program, workout program, periodization, mesocycle, RPE, volume training",
    feedSubtitle: "Powerbuilding programming, the builder, and shareable programs",
    ogDescription: "Build powerbuilding programs and share them in one link. Free, mobile-first, coach-friendly.",
    appTitle: "Program builder — powerbuild.ing",
    appDescription: "Build and edit training programs. Mesocycles, weeks, sets, reps, RPE, and shareable program links.",
    appOgTitle: "powerbuild.ing — Free Powerbuilding Program Builder",
    appOgDescription:
      "Create and share training programs instantly. No signup, no spreadsheets — just share a link.",
    knowledgePhrase: "open powerbuilding knowledge",
    llmsPositioning:
      "- powerbuild.ing is a **free powerbuilding program builder**.\n- Build hypertrophy and strength blocks, then **share them as a single link**.",
    llmsSearchTerms:
      "- powerbuilding program / hypertrophy program builder / strength program\n- periodization / mesocycle / volume block / strength block / RPE / %1RM",
    legalSport: "powerbuilding and general strength training",
    blogIndexLead:
      "Powerbuilding programming, how the builder works, and tips for sharing training plans.",
    blogCtaText:
      "Plan mesocycles, log sets with %1RM and RPE, and share one link. Free, no signup.",
    blogDefaultSection: "Powerbuilding",
    welcomeDialogTitle: "Welcome to powerbuild.ing",
    featuresVariablesHeading: "Training variables",
    articleMeetPrepLine: "real training blocks use all three",
    faqReplacements: [
      [/powerlift\.ing/g, "powerbuild.ing"],
      [/powerlifting/gi, (m) => (m[0] === "P" ? "Powerbuilding" : "powerbuilding")],
      [/squat, bench, and deadlift/g, "your main lifts"],
      [/squat, bench, and deadlift maxes/g, "your lift maxes"],
      [/SBD/g, "training"],
      [/SBD variables/g, "Training variables"],
      [/SBD days/g, "training days"],
      [/powerlifting program builder/gi, "powerbuilding program builder"],
      [/powerlifting program/gi, "powerbuilding program"],
      [/powerlifting templates/gi, "powerbuilding templates"],
      [/powerlifting knowledge/gi, "powerbuilding knowledge"],
      [/3-day SBD, 5\/3\/1, bench focus, meet prep/g, "splits, volume blocks, and strength templates"],
      [/hypertrophy phase, strength block, or meet prep/g, "hypertrophy phase, strength block, or peaking block"],
      [/bench focus/g, "upper-body focus"],
      [/3-day training, 5\/3\/1/g, "push/pull splits"],
      [/real meet prep uses all three/g, "real training blocks use all three"],
      [/log SBD work with/g, "log your work with"],
      [/Powerlifting programming/g, "Powerbuilding programming"],
      [/Welcome to Powerlift\.ing/gi, "Welcome to powerbuild.ing"],
      [/Welcome to powerlift\.ing/gi, "Welcome to powerbuild.ing"],
    ],
  },
  olympiclifting: {
    key: "olympiclifting",
    domain: "olympiclift.ing",
    slug: "olympiclift",
    wordmarkName: "Olympiclift",
    tld: "ing",
    comment: "olympiclift.ing — design tokens (Olympic weightlifting)",
    primary: "#2563eb",
    primaryDim: "#1d4ed8",
    chalk: "#f4f6f8",
    iron: "#0c0e14",
    steel: "#151820",
    rack: "#1c2030",
    rackUp: "#262c40",
    fontDisplay: '"Finlandica", system-ui, sans-serif',
    fontSans: '"DM Sans", system-ui, -apple-system, sans-serif',
    fontMono: '"IBM Plex Mono", ui-monospace, monospace',
    fontDisplayFallback: "system-ui, -apple-system, sans-serif",
    fontSansFallback: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
    fontMonoFallback: 'ui-monospace, "Cascadia Mono", "Segoe UI Mono", monospace',
    googleFontsUrl:
      "https://fonts.googleapis.com/css2?family=Finlandica:wght@400;500;600;700&family=DM+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@500;600&display=swap",
    appGoogleFontsUrl:
      "https://fonts.googleapis.com/css2?family=Finlandica:wght@400;500;600;700&family=DM+Sans:ital,wght@0,400;0,500;0,600;0,700;1,400&family=IBM+Plex+Mono:wght@500;600&display=swap",
    themeColorLight: "#f4f6fa",
    themeColorDark: "#0c0e14",
    sport: "Olympic weightlifting",
    sportTitle: "Olympic lifting",
    productLine: "Olympic lifting program builder",
    productShort: "Olympic lifting program builder",
    heroEm: "Share your whole week in one link",
    heroLead:
      "Plan mesocycles, weeks, and snatch & clean‑and‑jerk days — sets, reps, load, %1RM, RPE, and rest. Built for the platform on your phone.",
    featuresLead: "Technique blocks, strength phases, or meet prep — without leaving the browser.",
    featuresCard1: "Technique, strength, peaking — organize blocks and weeks in one view.",
    featuresCard2: "Sets, reps, load (lb/kg), %1RM, RPE, rest, and lift variations.",
    programsTitle: "Free Olympic lifting programs",
    programsLead:
      "Free weightlifting templates from olympiclift.ing. Pick a card, open it in the builder, edit anything, and share your version as one link. Use the <strong>Blank program</strong> card to start from scratch.",
    programsMeta:
      "Free Olympic lifting program templates on olympiclift.ing: technique weeks, strength blocks, and more. Open in the builder and share one link.",
    programsCardEditor: "Open in the olympiclift.ing editor",
    faqLandingLead: "Common questions about building, sharing, and using programs on olympiclift.ing",
    faqPageMeta:
      "Frequently asked questions about olympiclift.ing: free program builder, open sharing, %1RM maxes, coaches, and technical support.",
    tagline: "Free Olympic lifting program builder. Share whole programs as one open link.",
    description:
      "The best free Olympic lifting program builder. Plan mesocycles, track sets, reps, RPE, and %1RM — then share your whole training week in one link.",
    keywords:
      "Olympic lifting program, weightlifting program builder, snatch program, clean and jerk, strength program, periodization, mesocycle, RPE",
    feedSubtitle: "Olympic lifting programming, the builder, and shareable programs",
    ogDescription: "Build Olympic lifting programs and share them in one link. Free, mobile-first, coach-friendly.",
    appTitle: "Program builder — olympiclift.ing",
    appDescription: "Build and edit weightlifting programs. Mesocycles, weeks, sets, reps, RPE, and shareable program links.",
    appOgTitle: "olympiclift.ing — Free Olympic Lifting Program Builder",
    appOgDescription:
      "Create and share weightlifting programs instantly. No signup, no spreadsheets — just share a link.",
    knowledgePhrase: "open weightlifting knowledge",
    llmsPositioning:
      "- olympiclift.ing is a **free Olympic lifting program builder**.\n- Plan snatch and clean & jerk work, then **share the block as a single link**.",
    llmsSearchTerms:
      "- Olympic lifting program / weightlifting program builder / snatch and clean & jerk\n- periodization / mesocycle / technique block / strength block / RPE / %1RM",
    legalSport: "Olympic weightlifting and strength training",
    blogIndexLead:
      "Olympic lifting programming, the builder, and shareable training weeks.",
    blogCtaText:
      "Plan mesocycles, log snatch and C&J work with %1RM and RPE, and share one link. Free, no signup.",
    blogDefaultSection: "Olympic lifting",
    welcomeDialogTitle: "Welcome to olympiclift.ing",
    featuresVariablesHeading: "Lift variables",
    articleMeetPrepLine: "competition prep uses all three",
    faqReplacements: [
      [/powerlift\.ing/g, "olympiclift.ing"],
      [/powerlifting/gi, (m) => (m[0] === "P" ? "Olympic lifting" : "Olympic lifting")],
      [/squat, bench, and deadlift/g, "the snatch and clean & jerk"],
      [/squat, bench, and deadlift maxes/g, "your competition lift maxes"],
      [/SBD/g, "lifts"],
      [/SBD variables/g, "Lift variables"],
      [/SBD days/g, "training days"],
      [/powerlifting program builder/gi, "Olympic lifting program builder"],
      [/powerlifting program/gi, "Olympic lifting program"],
      [/powerlifting templates/gi, "Olympic lifting templates"],
      [/powerlifting knowledge/gi, "weightlifting knowledge"],
      [/3-day SBD, 5\/3\/1, bench focus, meet prep/g, "technique weeks, strength blocks, and peaking"],
      [/pause bench/g, "power variations"],
      [/hypertrophy phase, strength block, or meet prep/g, "technique phase, strength block, or competition prep"],
      [/bench focus/g, "snatch focus"],
      [/3-day lifts, 5\/3\/1/g, "technique weeks"],
      [/real meet prep uses all three/g, "competition prep uses all three"],
      [/log SBD work with/g, "log snatch and C&J work with"],
      [/Powerlifting programming/g, "Olympic lifting programming"],
      [/Welcome to Powerlift\.ing/gi, "Welcome to olympiclift.ing"],
      [/Welcome to powerlift\.ing/gi, "Welcome to olympiclift.ing"],
      [/SBD variables/g, "Lift variables"],
    ],
  },
  bootybuilding: {
    key: "bootybuilding",
    domain: "bootybuild.ing",
    slug: "bootybuild",
    tld: "ing",
    comment: "bootybuild.ing — design tokens (sleek female-tech)",
    primary: "#ff2a8f",
    primaryDim: "#e8007a",
    chalk: "#f8f4fc",
    iron: "#08040c",
    steel: "#100814",
    rack: "#1a0e18",
    rackUp: "#261622",
    fontDisplay: '"Syne", system-ui, sans-serif',
    fontSans: '"Plus Jakarta Sans", system-ui, -apple-system, sans-serif',
    fontDisplayFallback: "system-ui, -apple-system, sans-serif",
    fontSansFallback: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
    googleFontsUrl:
      "https://fonts.googleapis.com/css2?family=Syne:wght@600;700&family=Plus+Jakarta+Sans:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap",
    appGoogleFontsUrl:
      "https://fonts.googleapis.com/css2?family=Syne:wght@600;700&family=Plus+Jakarta+Sans:ital,wght@0,400;0,500;0,600;0,700;1,400&family=JetBrains+Mono:wght@500;600&display=swap",
    themeColorLight: "#f8f4fc",
    themeColorDark: "#08040c",
    sport: "glute training",
    sportTitle: "Bootybuilding",
    productLine: "Glute program builder",
    productShort: "glute program builder",
    heroEm: "Share your lower-body block in one link",
    heroLead:
      "Plan mesocycles, weeks, and glute-focused days — sets, reps, load, %1RM, RPE, and rest. Built for the gym floor on your phone.",
    featuresLead: "Hypertrophy waves, strength phases, or deloads — without leaving the browser.",
    featuresCard1: "Hypertrophy, strength, deload — organize blocks and weeks in one view.",
    featuresCard2: "Sets, reps, load (lb/kg), %1RM, RPE, rest, and exercise variations.",
    programsTitle: "Free glute & leg programs",
    programsLead:
      "Free lower-body templates from bootybuild.ing. Pick a card, open it in the builder, edit anything, and share your version as one link. Use the <strong>Blank program</strong> card to start from scratch.",
    programsMeta:
      "Free glute and leg program templates on bootybuild.ing: hip thrusts, RDLs, splits, and more. Open in the builder and share one link.",
    programsCardEditor: "Open in the bootybuild.ing editor",
    faqLandingLead: "Common questions about building, sharing, and using programs on bootybuild.ing",
    faqPageMeta:
      "Frequently asked questions about bootybuild.ing: free program builder, open sharing, %1RM maxes, coaches, and technical support.",
    tagline: "Free glute program builder. Share whole programs as one open link.",
    description:
      "The best free glute program builder. Plan mesocycles, track sets, reps, RPE, and %1RM — then share your whole lower-body block in one link.",
    keywords:
      "glute program, booty workout program, leg day program builder, hypertrophy, hip thrust, RPE, strength program",
    feedSubtitle: "Glute-focused programming, the builder, and shareable programs",
    ogDescription: "Build glute and leg programs and share them in one link. Free, mobile-first, coach-friendly.",
    appTitle: "Program builder — bootybuild.ing",
    appDescription: "Build and edit training programs. Mesocycles, weeks, sets, reps, RPE, and shareable program links.",
    appOgTitle: "bootybuild.ing — Free Glute Program Builder",
    appOgDescription:
      "Create and share training programs instantly. No signup, no spreadsheets — just share a link.",
    knowledgePhrase: "open training knowledge",
    llmsPositioning:
      "- bootybuild.ing is a **free glute-focused program builder**.\n- Plan lower-body blocks, then **share them as a single link**.",
    llmsSearchTerms:
      "- glute program / leg day program builder / hip thrust program\n- periodization / mesocycle / hypertrophy block / RPE / %1RM",
    legalSport: "general strength and hypertrophy training",
    blogIndexLead:
      "Glute-focused programming, the builder, and shareable leg-day blocks.",
    blogCtaText:
      "Plan mesocycles, log lower-body work with %1RM and RPE, and share one link. Free, no signup.",
    blogDefaultSection: "Glute training",
    welcomeDialogTitle: "Welcome to bootybuild.ing",
    featuresVariablesHeading: "Training variables",
    articleMeetPrepLine: "hard hypertrophy blocks use all three",
    faqReplacements: [
      [/powerlift\.ing/g, "bootybuild.ing"],
      [/powerlifting/gi, (m) => (m[0] === "P" ? "Glute training" : "glute training")],
      [/squat, bench, and deadlift/g, "your main lower-body lifts"],
      [/squat, bench, and deadlift maxes/g, "your lift maxes"],
      [/SBD/g, "training"],
      [/SBD variables/g, "Training variables"],
      [/SBD days/g, "training days"],
      [/powerlifting program builder/gi, "glute program builder"],
      [/powerlifting program/gi, "training program"],
      [/powerlifting templates/gi, "glute and leg templates"],
      [/powerlifting knowledge/gi, "training knowledge"],
      [/3-day SBD, 5\/3\/1, bench focus, meet prep/g, "glute splits, hip thrust blocks, and leg templates"],
      [/pause bench/g, "variations"],
      [/hypertrophy phase, strength block, or meet prep/g, "hypertrophy phase, strength block, or deload"],
      [/bench focus/g, "glute focus"],
      [/3-day training, 5\/3\/1/g, "glute splits"],
      [/real meet prep uses all three/g, "hard hypertrophy blocks use all three"],
      [/log SBD work with/g, "log lower-body work with"],
      [/Powerlifting programming/g, "Glute-focused programming"],
      [/Welcome to Powerlift\.ing/gi, "Welcome to bootybuild.ing"],
      [/Welcome to powerlift\.ing/gi, "Welcome to bootybuild.ing"],
      [/SBD variables/g, "Training variables"],
    ],
  },
  itraining: {
    key: "itraining",
    domain: "itrain.ing",
    slug: "itrain",
    wordmarkName: "iTrain",
    tld: "ing",
    comment: "itrain.ing — design tokens (true monochrome UI)",
    primary: "#e8e8ec",
    primaryDim: "#9ca3af",
    chalk: "#ffffff",
    iron: "#000000",
    steel: "#0a0a0a",
    rack: "#141414",
    rackUp: "#1a1a1a",
    fontDisplay: '"Outfit", system-ui, sans-serif',
    fontSans: '"DM Sans", system-ui, -apple-system, sans-serif',
    fontMono: '"IBM Plex Mono", ui-monospace, monospace',
    fontDisplayFallback: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
    fontSansFallback: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
    fontMonoFallback: 'ui-monospace, "Cascadia Mono", "Segoe UI Mono", monospace',
    googleFontsUrl:
      "https://fonts.googleapis.com/css2?family=Outfit:wght@500;600;700&family=DM+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@500;600&display=swap",
    appGoogleFontsUrl:
      "https://fonts.googleapis.com/css2?family=Outfit:wght@500;600;700&family=DM+Sans:ital,wght@0,400;0,500;0,600;0,700;1,400&family=IBM+Plex+Mono:wght@500;600&display=swap",
    themeColorLight: "#ffffff",
    themeColorDark: "#000000",
    sport: "training",
    sportTitle: "Training",
    productLine: "Training program builder",
    productShort: "training program builder",
    heroEm: "Share your whole program in one link",
    heroLead:
      "Plan mesocycles, weeks, and training days — sets, reps, load, %1RM, RPE, and rest. Built for any strength block on your phone.",
    featuresLead: "Hypertrophy, strength, peaking, or deload — without leaving the browser.",
    featuresCard1: "Hypertrophy, strength, peaking — organize blocks and weeks in one view.",
    featuresCard2: "Sets, reps, load (lb/kg), %1RM, RPE, rest, and exercise variations.",
    programsTitle: "Free training programs",
    programsLead:
      "Free strength templates from itrain.ing. Pick a card, open it in the builder, edit anything, and share your version as one link. Use the <strong>Blank program</strong> card to start from scratch.",
    programsMeta:
      "Free training program templates on itrain.ing: splits, strength blocks, and peaking templates. Open in the builder and share one link.",
    programsCardEditor: "Open in the itrain.ing editor",
    faqLandingLead: "Common questions about building, sharing, and using programs on itrain.ing",
    faqPageMeta:
      "Frequently asked questions about itrain.ing: free program builder, open sharing, %1RM maxes, coaches, and technical support.",
    tagline: "Free training program builder. Share whole programs as one open link.",
    description:
      "The best free training program builder. Plan mesocycles, track sets, reps, RPE, and %1RM — then share your whole program in one link.",
    keywords:
      "training program, workout program builder, strength program, periodization, mesocycle, RPE, gym program",
    feedSubtitle: "Training programming, the builder, and shareable programs",
    ogDescription: "Build training programs and share them in one link. Free, mobile-first, coach-friendly.",
    appTitle: "Program builder — itrain.ing",
    appDescription: "Build and edit training programs. Mesocycles, weeks, sets, reps, RPE, and shareable program links.",
    appOgTitle: "itrain.ing — Free Training Program Builder",
    appOgDescription:
      "Create and share training programs instantly. No signup, no spreadsheets — just share a link.",
    knowledgePhrase: "open training knowledge",
    llmsPositioning:
      "- itrain.ing is a **free training program builder**.\n- Plan strength blocks, then **share them as a single link**.",
    llmsSearchTerms:
      "- training program / workout program builder / strength program\n- periodization / mesocycle / hypertrophy block / RPE / %1RM",
    legalSport: "general strength and conditioning",
    blogIndexLead:
      "Training programming, how the builder works, and tips for sharing plans with athletes and partners.",
    blogCtaText:
      "Plan mesocycles, log work with %1RM and RPE, and share one link. Free, no signup.",
    blogDefaultSection: "Training",
    welcomeDialogTitle: "Welcome to itrain.ing",
    featuresVariablesHeading: "Training variables",
    articleMeetPrepLine: "real training blocks use all three",
    faqReplacements: [
      [/powerlift\.ing/g, "itrain.ing"],
      [/powerlifting/gi, (m) => (m[0] === "P" ? "Training" : "training")],
      [/squat, bench, and deadlift/g, "your main lifts"],
      [/squat, bench, and deadlift maxes/g, "your lift maxes"],
      [/SBD/g, "training"],
      [/SBD variables/g, "Training variables"],
      [/SBD days/g, "training days"],
      [/powerlifting program builder/gi, "training program builder"],
      [/powerlifting program/gi, "training program"],
      [/powerlifting templates/gi, "training templates"],
      [/powerlifting knowledge/gi, "training knowledge"],
      [/3-day SBD, 5\/3\/1, bench focus, meet prep/g, "splits, strength blocks, and peaking templates"],
      [/hypertrophy phase, strength block, or meet prep/g, "hypertrophy phase, strength block, or peaking block"],
      [/bench focus/g, "upper-body focus"],
      [/3-day training, 5\/3\/1/g, "3-day splits"],
      [/real meet prep uses all three/g, "real training blocks use all three"],
      [/log SBD work with/g, "log your work with"],
      [/Powerlifting programming/g, "Training programming"],
      [/Welcome to Powerlift\.ing/gi, "Welcome to itrain.ing"],
      [/Welcome to powerlift\.ing/gi, "Welcome to itrain.ing"],
    ],
  },
};
